/*
 * errepi-rs - Rust bindings for Errepi Net microservices
 *
 * Copyright © 2023-2026 Errepi Net S.R.L.
 * Author: Valerio Faiuolo <valerio.faiuolo@errepinet.it>
 *
 * All rights reserved. This software is the property of Errepi Net S.R.L.
 * Unauthorized copying, modification, distribution, or use of this software,
 * via any medium, is strictly prohibited without express written permission.
 */

//! Cron domain models.
//!
//! Mirrors the pydantic v2 models of `errepi-py` `errepi/cron/models.py`.

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Job configuration, including max retries and retry delay.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CronConfiguration {
    /// Maximum number of retries for a job.
    pub job_max_retries: u32,
    /// Delay in seconds between retries.
    pub job_retry_delay_secs: u32,
    /// Datetime when the configuration was set (absent on set payloads).
    pub set_at: Option<DateTime<Utc>>,
}

/// Type of HTTP job body (Json or Text).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum JobBodyType {
    Json,
    Text,
}

/// Result of a job execution.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobExecutionResult {
    /// Datetime of the execution.
    pub date_time: DateTime<Utc>,
    /// Execution detail message.
    pub detail: String,
    /// Whether the execution was successful.
    pub is_success: bool,
    /// ID of the executed job.
    pub job_id: String,
    /// Namespace of the executed job.
    pub namespace: String,
}

/// Job execution frequency (hourly, daily, weekly, monthly, or by minute).
///
/// Mirrors the `JobFrequency` RootModel of `errepi-py`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum JobFrequency {
    Hour(u32),
    Day(u32),
    Week(u32),
    Month(u32),
    Minute(u32),
}

/// Supported HTTP methods for jobs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum JobHttpMethod {
    Get,
    Post,
    Patch,
    Put,
    Delete,
}

/// Job status values.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum JobStatus {
    Scheduled,
    Rescheduled,
    RetryScheduled,
    Ok,
    Failed,
}

/// Reference to a configuration or value with timestamp.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Ref {
    /// Datetime when the value was set.
    pub setted_at: DateTime<Utc>,
    /// The referenced value.
    pub value: String,
}

/// Payload for creating or updating a reference.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RefCreateUpdate {
    /// The value to set or update.
    pub value: String,
}

/// Definition of an HTTP job, with parameters such as URL, method, body, and
/// headers.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct HTTPJob {
    /// Optional request body as a string.
    pub body: Option<String>,
    /// Optional type of the request body (Json or Text).
    pub body_type: Option<JobBodyType>,
    /// Optional dictionary of HTTP headers.
    pub headers: Option<HashMap<String, String>>,
    /// HTTP method to use for the job.
    pub method: JobHttpMethod,
    /// Optional timeout in seconds for the request.
    pub timeout_seconds: Option<u64>,
    /// Target URL for the HTTP request.
    pub url: String,
    /// Optional user agent string.
    pub user_agent: Option<String>,
    /// Optional list of valid HTTP status codes.
    pub valid_http_codes: Option<Vec<u32>>,
}

/// Generic job type, currently only HTTP is supported.
///
/// Mirrors the `JobType` RootModel of `errepi-py`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum JobType {
    Http(HTTPJob),
}

/// Represents a scheduled job, with configuration, status, type, and
/// frequency.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Job {
    /// Autogenerated job ID.
    pub id: Option<String>,
    /// Optional job description.
    pub description: Option<String>,
    /// Optional job execution frequency.
    pub frequency: Option<JobFrequency>,
    /// Datetime when the job was created.
    pub created: DateTime<Utc>,
    /// Datetime of the last update.
    pub updated: Option<DateTime<Utc>>,
    /// Datetime of the last execution.
    pub last_execution_dt: Option<DateTime<Utc>>,
    /// Datetime of the next scheduled execution.
    pub next_execution_dt: DateTime<Utc>,
    /// Whether the job is enabled.
    pub enabled: bool,
    /// Type of the job.
    pub job_type: JobType,
    /// Current status of the job.
    pub job_status: JobStatus,
    /// Job configuration entry.
    pub configuration: CronConfiguration,
    /// Current number of retries.
    pub curr_retries: u32,
}

/// Payload for creating or updating a job.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobCreateUpdate {
    /// Optional job description.
    pub description: Option<String>,
    /// Whether the job is enabled.
    pub enabled: bool,
    /// Optional job execution frequency.
    pub frequency: Option<JobFrequency>,
    /// Type of the job.
    pub job_type: JobType,
    /// Datetime in UTC of the next scheduled execution.
    pub next_execution_dt: DateTime<Utc>,
    /// Optional configuration ID to use.
    pub use_configuration: Option<String>,
}
